services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    env_file: .env
    environment:
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}

  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
    env_file: .env
    environment:
      - DATABASE_URL:${DATABASE_URL}

volumes:
  node_modules:
